### ISSUE TITLE
strong tag not showing up in Chrome

### ISSUE THREAD

**Issue by mvs202** [transpocamp/transportationcamp.org#26]
the `**` and `__` markdown are being turned into `<strong>` tags...but with no effect in Chrome. I suspect it's because of the font we're using. It works fine in Safari and Firefox.

**Comment by kurtraschke** [comment]
Seems to be working for me:

<img width="378" alt="screen shot 2016-09-19 at 6 13 37 pm" src="https://cloud.githubusercontent.com/assets/118546/18650775/e71924c6-7e94-11e6-9bc0-cebf6d436f46.png">

(Chrome 52.0.2743.116 on OS X 10.11.6)
